ALTER TABLE CLIENTE
ADD CONSTRAINT chk_cpf CHECK (LENGTH(cpf) = 11);

ALTER TABLE PEDIDO
ADD CONSTRAINT chk_status_pedido 
CHECK (status_pedido IN ('ABERTO', 'EM PRODUCAO', 'FINALIZADO', 'CANCELADO'));

ALTER TABLE ETAPA_PRODUCAO
ADD CONSTRAINT chk_datas_etapa
CHECK (data_fim IS NULL OR data_fim >= data_inicio);

ALTER TABLE PROTESE
ADD CONSTRAINT chk_tipo_protese
CHECK (tipo IN ('FIXA','MOVEL','IMPLANTE','TOTAL'));
